### PR TITLE
Show active navbar item

### PR DESCRIPTION
**Pull request by Masterjun3**
image

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Does it make sense to make the rest also a bit lighter? I have this complaint since the very beginning but I don't remember if I told anyone :D

**Comment by TiKevin83** [comment]
I'll check it against accessibility

**Comment by TiKevin83** [comment]
Can you add this to `bootstrap-overrides.scss` to hit WCAG AAA on the contrast in the navbar?
```
.navbar-dark .navbar-nav .nav-link {
	color: RGBA(255,255,255,.6);
}
```

**Comment by Masterjun3** [comment]
Now looks like this:
image

**Review by TiKevin83 — APPROVED** [review]

**Review by adelikat — APPROVED** [review]

**Pull request merged**
