### PR TITLE
Breadcrumbs on Wiki pages, replacing Parents list

### PR DESCRIPTION
**Pull request by Masterjun3**
Clickable navigation.

(before | after)
image

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Wow this is awesome! You really can click each parent separately?

**Comment by Masterjun3** [comment]
Yes! :D

**Review by TiKevin83 — APPROVED** [review]

**Comment by adelikat** [comment]
Yaaaaaas

**Comment by TiKevin83** [comment]
fixed #588

**Pull request merged**
