### PR TITLE
highlight terms with a background color

### LINKED ISSUE #974: Term definition misses BG color
https://tasvideos.org/TextFormattingRules#Lists

изображение

Old site

изображение

Also explanation used to be shifted from the term.

### PR DESCRIPTION
**Pull request by TiKevin83**
fixes #974
dtStyleDark
dtStyleLight

### CODE REVIEW

**Comment by TiKevin83** [comment]
I tried making the highlight more separate from the background and it looks pretty bad, I think it looks fine with the slight background difference

**Comment by vadosnaprimer** [comment]
It's bad even with this?

изображение

**Review by Masterjun3 — APPROVED** [review]
I didn't even see the colors on my phone, but on my desktop monitor it looks fine. I'd personally separate them even more from the background, but if you say you tried it and it looked bad, then it's fine.
It's certainly better than what we had before.

**Comment by TiKevin83** [comment]
> It's bad even with this BG?
> 
> изображение

Yeah the cardprimary color for some reason doesn't look great to me on light mode in that context
image

**Comment by vadosnaprimer** [comment]
IMO it looks awesome :D

**Pull request merged**
