### PR TITLE
Recategorize Homepage Nav Menu

### LINKED ISSUE #680: Restore the "About" option in the navigation
On the old page it's a tab linking our information page "WelcomeToTASVideos".
This option is currently hidden in the "Home" dropdown (which very much shouldn't be a dropdown, but that can be a different issue), and is poorly titled "Welcome". It should be "About" like on the old page and it's own option, preferably at the very right end of the list.

We do have the Welcome banner, but it only appears on the frontpage. A lot of links are to publications where the banner doesn't appear.

This tab is incomparably important to absolute first timers to our page. So important in fact that I personally count it as go-live critical.

### PR DESCRIPTION
**Pull request by TiKevin83**
fixes #680

### CODE REVIEW

**Comment by TiKevin83** [comment]
image

**Comment by ThunderAxe31** [comment]
Looks excellent. My only objection is for using the vague term "chat". People may mistakenly expect it to be a site built-in chat, and thus be discouraged from joining, for various reasons. I think it would be much better to either write "Discord" or put the Discord icon (with varying size depending on client system, like the rest). https://discord.com/assets/847541504914fd33810e70a0ea73177e.ico

**Comment by vadosnaprimer** [comment]
> Looks excellent. My only objection is for using the vague term "chat". People may mistakenly expect it to be a site built-in chat, and thus be discouraged from joining, for various reasons. I think it would be much better to either write "Discord" or put the Discord icon (with varying size depending on client system, like the rest). https://discord.com/assets/847541504914fd33810e70a0ea73177e.ico

What about renaming it to Chats? We still host IRC and stuff.

**Comment by meshuggahtas** [comment]
The legacy site has **Chat** in the menu and **Live Chat** after clicking it. I think chat is a known word internationally (because of chat clients, chat rooms, etc) and describes it's intended feature enough. 

Personally, **Chats** sounds bizarre. Just googled it and there is a "The Chats" artist, Viber Chats and another one. Every other result is Chat for me.

**Comment by meshuggahtas** [comment]
I have a very beginning draft of important links, it looks like this (ignore the order of submenu):
WelcomeToTASVideos (About @ menu)
- Community
- Users
- SiteHistory
- Helping

Rules and guidelines
- SiteRules
- TextFormattingRules
- MovieRules

Game informations
- Games
- GameResources

From http://tasvideos.org/MESHUGGAH/CheatSheet.html

**Comment by ThunderAxe31** [comment]
> What about renaming it to Chats? We still host IRC and stuff.

IRC is dying, while Discord is growing. Most people that still hang around on our IRC channel (which are few and decreasing) are also present in the Discord server.

But hey, if you still think that IRC needs to be mentioned, then let's display like this in the navbar: 847541504914fd33810e70a0ea73177e-000/IRC
This way we can have both hyperlinks while saving even more space!

**Review by Masterjun3 — APPROVED** [review]
This is a good and important change. It should be merged before going live. More navbar changes can come later after more discussions. Ah, and this resolves #680.

**Comment by vadosnaprimer** [comment]
> But hey, if you still think that IRC needs to be mentioned, then let's display like this in the navbar: 847541504914fd33810e70a0ea73177e-000/IRC This way we can have both hyperlinks while saving even more space!

IMO it visually feels worse than the word Chat.

**Review by vadosnaprimer — APPROVED** [review]

**Pull request merged**
