### PR TITLE
Minor frontend improvements for search results page

### PR DESCRIPTION
**Pull request by YoshiRulz**

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Can you post before/after pics?

**Comment by YoshiRulz** [comment]
before
before
after
after

**Comment by YoshiRulz** [comment]
https://github.com/TASVideos/tasvideos/blob/b41b6cc3180fcc2ebdac5f537d1d5d8594059359/TASVideos/Pages/Search/Index.cshtml#L52
And the reason was to make it even clearer that it's not one of the results.

**Comment by vadosnaprimer** [comment]
> And the reason was to make it even clearer that it's not one of the results.

I don't believe anyone would seriously think `...` without a link is a movie/publication.

**Comment by adelikat** [comment]
Closing because this UI change was not desired by staff

**Comment by YoshiRulz** [comment]
The game groups really need *a* separator. How about ','?
```diff
-<a asp-page="/GameGroups/Index" asp-route-id="@group.Id">@group.Name</a>
+<a asp-page="/GameGroups/Index" asp-route-id="@group.Id" class="game-search-result-group">@group.Name</a>
```
```diff
+.game-search-result-group:not(:last-of-type)::after {
+	color: var(--bs-body-color);
+	content: ",";
+}
```

**Comment by Masterjun3** [comment]
Can you make a screenshot of what exactly needs a separator? I don't seem to understand what the issue is.
If it's more elaborate we can also make a new issue ticket about this.

**Comment by vadosnaprimer** [comment]
изображение

изображение

**Pull request closed without merging**
