### PR TITLE
Attempt to improve Media Notification Messages

### LINKED ISSUE #1001: Discord embeds for posts and topics should show the subforum.
Instead of just showing the title in the description, it should add the subforum. This adds very useful information about the topic. Ideally it takes the same format as on the forums, that is, with an arrow symbol:
For topics the embeds that now look like `PCem and 86Box` it would look like `BizHawk → PCem and 86Box`.
For posts the embeds looking like `Thread Topic: Strange Issue` would look like `FCEUX → Strange Issue`.

### PR DESCRIPTION
**Pull request by Masterjun3**
- Remove most embeds from discord and leave them only for publications, submissions, topics, and news posts.
- Fix several formatting issues (e.g. "added added")
- Make messages more consistent with each other.
- Format messages to prevent important information at the end being capped by character limits.
- Resolves #1001.

### CODE REVIEW

**Comment by Spikestuff** [comment]
One issue that I've noticed is that it informs of the Game Name on Submission edits however on Publication edits the Game Name isn't there.

**Comment by Masterjun3** [comment]
Yeah I removed that to prevent the clutter.

**Comment by Spikestuff** [comment]
Conversation moved to Discord, mainly cause I couldn't remember my account to GitHub on mobile.
> Spikestuff: Why is Submissions **showing** the Game Name but Publications **aren't** when they get edited?
> Spikestuff: It would be better to know what movie was edited on both sides not just one. 
> Spikestuff: This removes something that should've remained.
> Spikestuff: Saying it "removes clutter" is very contradictory when Submission Game Name is still viewable but Publication Game Name isn't.
> Masterjun: Yeah I can readd things, the reason for the difference is that there are only 2 fields, so the Pubs show "Pub edited"+"[what exactly was edited]" and Subs only show "Sub edited"+"[Title]"
> Spikestuff: So something to solve then.
> Masterjun: you probably don't want me to remove the titles from the subs as well, right? :D
> Spikestuff: Clearly not.

Currently just to illustrate the difference between Publications and Submissions a bit better:
> 4574M edited by Zinfidel (Poking the YT updater) https://tasvideos.org/4574M

Meanwhile for comparison:
> Post edited by Samsara (WorkB: #7283: Samsara & Spikestuff's Genesis Barney's Hide & Seek Game in 04:54.51) https://tasvideos.org/Forum/Posts/511662

Why is it not possible for:
> 4574M (PSX Bishi Bashi Special 3: Step Champ) edited by Zinfidel (Poking the YT updater) https://tasvideos.org/4574M

To be a thing?
This solves things on the end user to know what the Publication movie is being edited.
Actually the better question is why did you remove something that simplified things on the end user to know what was edited,? Since after all it initially had it, albeit being a bit annoying since it was all embedded.

**Comment by Masterjun3** [comment]
I already restored it #1024.

**Comment by Spikestuff** [comment]
Ah. Well, danke Masterjun... wished you told me you actually did that, _but hey_ also preservation sake.

**Comment by Masterjun3** [comment]
Yeah sorry, kind of forgot to tell you about it.

**Pull request merged**
