### PR TITLE
New Pager design

### PR DESCRIPTION
**Pull request by Masterjun3**
(before | after)
image

Dropdowns:
image

### CODE REVIEW

**Comment by Masterjun3** [comment]
I tried to change the style of the buttons so that the shadow isn't there when it's active, but I have a hard time understanding all of those css customizations, so that can be a separate thing.

**Comment by Masterjun3** [comment]
- First & Second are always visible
- Second-to-last & Last are always visible
- Previous page & Current page & Next page are always visible
- [...] gets expanded when it has only 1 page

**Comment by Masterjun3** [comment]
Sort reset.
In case you sorted alphabetically or by author or others and want to return to default sort and don't want to remove all sort tags from the query in the url.

**Comment by vadosnaprimer** [comment]
I feel it would be better to have a text on it saying what it does.

**Comment by Masterjun3** [comment]
image

**Comment by ThunderAxe31** [comment]
Can we please put everything in a single row? Just to save vertical space.

**Comment by Masterjun3** [comment]
I tried, doesn't work well. I want the page list to be on the bottom always. If someone with more bootstrap skills can manage that, please pr or tell me.

**Pull request merged**
