### PR TITLE
Reorganize many things for space and simplicity

### PR DESCRIPTION
**Pull request by ThunderAxe31**
I reorganized a lot of the movie page interface, in order to save space and make it easier to navigate through. Here is the current list of changes: (Edit: doing less stuff at once, as per adelikat's request)
1. Star icon links to the Stars page.
2. Star and flag icons don't occupy whole columns, saving space for the next lines of the title on mobile devices.
3. ~~Rating buttons are right after the movie title.~~
4. ~~Movie file download moved to the the bottom, under Emulator version.~~
5. ~~Movie file download button converted to a plain hypertext.~~
6. Submission button renamed to Author notes.
7. ~~Submission and Discuss buttons moved in the bottor right of the movie description.~~
8. Edit, Catalog, Logs buttons moved in the last row of the page.
9. ~~Publication date moved to the bottom left of the movie description.~~
10. ~~Award pics moved under the bottom center of the movie description.~~
11. ~~Torrent links obliterated.~~

Comparison between current and new, desktop mode:

Comparison between current and new, mobile mode (top of page):

Comparison between current and new, mobile mode (bottom of page):

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
>     1. Star icon links to the Stars page.

Good.
 
>     2. Star and flag icons don't occupy whole columns, saving space for the next lines of the title on mobile devices.

Not sure. I think it's tiny enough not to matter.

>     3. Rating buttons are right after the movie title.

It's good that they're more visible, but titles have different lengths, so position of rating buttons will be different every time. I think there's better place for them, but I don't have good ideas.

>     4. Movie file download moved to the the bottom, under Emulator version.

Probably good, it's rare that people care about movie files. But what is the blue `Download` button for now?

>     5. Movie file download button converted to a plain hypertext.

There are other buttons there now, so I'd just move the button, without changing its text.

>     6. Submission button renamed to Author notes.

Still reads as `Submission` on your screenshots.

>     7. Submission and Discuss buttons moved in the bottor right of the movie description.

I don't mind.

>     8. Edit, Catalog, Logs buttons moved in the last row of the page.

I like this.

>     9. Publication date moved to the bottom left of the movie description.

I personally don't mind. I like that it now explains what that date is.

>     10. Award pics moved under the bottom center of the movie description.

I don't have a preference.

>     11. Torrent links obliterated.

Good!

**Comment by SamsaraTAS** [comment]
> 1. Star icon links to the Stars page.

Very good change.
> 2. Star and flag icons don't occupy whole columns, saving space for the next lines of the title on mobile devices.

I like the idea, though aesthetically it's a bit give or take. I could see people preferring either way.
> 3. Rating buttons are right after the movie title.

This isn't necessarily related to the PR, but if we want simplicity, I think it might be better to not have two separate buttons and two separate pages for ratings. We could just have a single button that gives the rating and number of votes and have it link to a page that allows you to both rate a movie and view everyone else's ratings. With that, I think the rating can stay right under the screenshot. Makes sense to keep it near the links to watching the movie, IMO.
> 4. Movie file download moved to the the bottom, under Emulator version.

I'll get to this.
> 5. Movie file download button converted to a plain hypertext.

I'll get to this as well.
> 6. Submission button renamed to Author notes.

This definitely makes more sense to me for a publication page.
> 7. Submission and Discuss buttons moved in the bottom right of the movie description.

Same as above, it makes more sense from a visual standpoint.
> 8. Edit, Catalog, Logs buttons moved in the last row of the page.

3x "makes more sense" combo.
> 9. Publication date moved to the bottom left of the movie description.

Masterjun brought this up on Discord and I think I agree with him here, I like having the date above the description.
> 10. Award pics moved under the bottom center of the movie description.

The overall placement is good, but it ties back into how the publication date should be back above the description. Awards should be left-aligned here, not awkwardly hanging out next to a date.
> 11. Torrent links obliterated.

What about the downloadable encode links? Is that why there's still a Download button next to the Watch button? If that's the case, that's probably going to mislead people into thinking they're downloading the input file.

Since we're still going to have downloadables, just not torrents, I think they should be where the current plaintext Movie File link is. The movie file link should honestly remain a button, and honestly I think the best place for it is next to the Author Notes and Discuss buttons.

**Comment by Masterjun3** [comment]
Can't really make a comprehensive comment right now, but my overall impression is that the new design is too "busy".

The existing design has clearly separated sections: title, image+description, interaction buttons, additional info. Each of the sections have their own consistent design: title has the one-line design, description is a simple text, the interactions are all buttons, and the additional info is a dotted list.

The proposed design scatters the buttons with similar design into all other areas. If they are in different places, stuff should look different.

**Comment by ThunderAxe31** [comment]
> > 3. Rating buttons are right after the movie title.
> 
> It's good that they're more visible, but titles have different lengths, so position of rating buttons will be different every time. I think there's better place for them, but I don't have good ideas.

The movie length also changes position all the time, but no one ever complained.

> > 4. Movie file download moved to the the bottom, under Emulator version.
> 
> Probably good, it's rare that people care about movie files. But what is the blue `Download` button for now?

It's for downloading the .mp4 encode, which will be the only one after killing the .mkv encoding.

> > 5. Movie file download button converted to a plain hypertext.
> 
> There are other buttons there now, so I'd just move the button, without changing its text.

I didn't change the text, I changed the appearance. It's not a button anymore, it's not a plain clickable link.

> > 6. Submission button renamed to Author notes.
> 
> Still reads as `Submission` on your screenshots.

Screenshots fixed.

**Comment by ThunderAxe31** [comment]
> > 9. Publication date moved to the bottom left of the movie description.
> 
> Masterjun brought this up on Discord and I think I agree with him here, I like having the date above the description.

Doesn't look too important to me. It's just that is saves precious space for the mobile version.

> > 10. Award pics moved under the bottom center of the movie description.
> 
> The overall placement is good, but it ties back into how the publication date should be back above the description. Awards should be left-aligned here, not awkwardly hanging out next to a date.

I totally agree, and I fixed that in my screeshots (soon also the PR). Now the awards are aligned to the right. Don't mind the three edit buttons, these aren't spawned for the 99.9% of the users anyway.

**Comment by ThunderAxe31** [comment]
> > 2. Star and flag icons don't occupy whole columns, saving space for the next lines of the title on mobile devices.
> 
> Not sure. I think it's tiny enough not to matter.

> > 2. Star and flag icons don't occupy whole columns, saving space for the next lines of the title on mobile devices.
> 
> I like the idea, though aesthetically it's a bit give or take. I could see people preferring either way.

Here is my strongest argument:
image

**Comment by vadosnaprimer** [comment]
> The movie length also changes position all the time, but no one ever complained.

It's because they don't have to click it to rate a movie. We need rating to be trivial to access, IMO if its position changes every time it makes it less trivial, less desired, annoying to use.

> It's for downloading the .mp4 encode, which will be the only one after killing the .mkv encoding.

The plan is having a system that recognizes and properly shows optional encodes that feature something unique the publisher felt like doing. Most common example is CamHack. Also maybe there will be lossless encodes at some point. Or encodes specifically crafted for TiKevin's site to appear as good as YT encodes. There definitely needs to be indication of what people are downloading exactly.

Overall I do think that the current view has too many buttons in one place, and only few of them are often needed for most people.

**Comment by ThunderAxe31** [comment]
> > The movie length also changes position all the time, but no one ever complained.
> 
> It's because they don't have to click it to rate a movie. We need rating to be trivial to access, IMO if its position changes every time it makes it less trivial, less desired, annoying to use.

Button placement also changes in any other spot. Under the movie screenshot, it changes vertical position depending on screenshot size. Under the movie description, it changes vertical position depending on text length.

Anyway, I can right-align the rating buttons, if you really insist. I'll figure out the code later.

> > It's for downloading the .mp4 encode, which will be the only one after killing the .mkv encoding.
> 
> The plan is having a system that recognizes and properly shows optional encodes that feature something unique the publisher felt like doing. Most common example is CamHack. Also maybe there will be lossless encodes at some point. Or encodes specifically crafted for TiKevin's site to appear as good as YT encodes. There definitely needs to be indication of what people are downloading exactly.

Yes, I also think that's important, but we should figure that after putting in place the layout for movies that only have one encode, which is the 99.9% of the published movies.

**Comment by ThunderAxe31** [comment]
Closing this due to confusing confusion happened. New PR: https://github.com/TASVideos/tasvideos/pull/693

**Pull request closed without merging**
