### PR TITLE
Improve UX for users looking to replace the movie files in their submissions

### PR DESCRIPTION
**Pull request by YoshiRulz**
screenshot

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
If people cancel and resubmit to fix a minor mistake, they haven't read Submission Instructions. I think the link we need within the description of that Movie file field is https://tasvideos.org/SubmissionInstructions#UpdatingTheSubmissionFile

Maybe just say there "if you need to do a minor fix to the movie, [here's how](https://tasvideos.org/SubmissionInstructions#UpdatingTheSubmissionFile)"

**Review by vadosnaprimer — CHANGES_REQUESTED** [review]
OK so please put an alert-info instead, at the top of submission edit page, and have a system wiki page whose text will be embedded there, similar to how Submissions/Submit embeds System/SubmitMovieHeader

**Comment by YoshiRulz** [comment]
Sorry for the churn.

I copied what the Submit page had, is that all that's necessary?

**Review by vadosnaprimer — APPROVED** [review]
Works perfectly now!

изображение

**Review by adelikat — APPROVED** [review]

**Pull request merged**
