### PR TITLE
Improve handling of "extlinks"

### PR DESCRIPTION
**Pull request by YoshiRulz**

### CODE REVIEW

**Comment by YoshiRulz** [comment]
@nattthebear Is this the right approach? It's working well now, but I foresee problems with trying to combine `rel` values—specifically, I'm thinking of adding `rel="ugc"` to only *some* wiki-format excerpts, but as I've written it that would override the other values. So I would need to pass `"noopener external nofollow ugc"` and then that has to be kept in sync. Is there an existing mechanism for combining `class` that I've overlooked?

**Comment by nattthebear** [comment]
@YoshiRulz I don't think you're missing any capabilities.  The system has about enough abstraction layers to handle what it does, but no more.

**Comment by YoshiRulz** [comment]
Then should I contribute first-class support for those attributes before finalising this?

**Comment by nattthebear** [comment]
If you think it's useful, I could see some sort of `rel` and `class` handling as a useful part of the `Node` capabilities.

**Review by adelikat — APPROVED** [review]

**Comment by adelikat** [comment]
@YoshiRulz : can you fix the merge conflicts in this PR? and then I'll merge

**Pull request merged**
