### PR TITLE
Add quote link to posts

### PR DESCRIPTION
**Pull request by Randomno**
#1207 

image

Very simple BBCode implementation. Should probably be sure about how we want to do this before going ahead with it.

### CODE REVIEW

**Comment by nattthebear** [comment]
This seems reasonable.  Ideally, this sort of markup wouldn't be baked into the post, but that ship sailed long before the current site, as the old site had the " wrote" text burned into posts as well.

Could we take another pass at the visuals though?  I feel like that single arrows are more commonly used for this sort of thing than double.

**Comment by vadosnaprimer** [comment]
Single arrow might look nicer but it should also be something easy to click, so I suggested wide arrows.

**Comment by nattthebear** [comment]
Is there a fat arrow we can use as opposed to double arrow?

**Comment by Masterjun3** [comment]
For me an up arrow actually implies that the page will be moved (like our "move up" button on the bottom right if you scroll down), where instead it's a link to a completely new page.
Maybe a [speech bubble icon](https://fontawesome.com/icons/comment?f=classic&s=solid) would work here, similar to how Discord does it:
image

**Comment by vadosnaprimer** [comment]
The bubble was very first suggestion, but maybe the post icon would work since it'd be in a different place.

**Comment by adelikat** [comment]
How about this one? https://fontawesome.com/icons/comment?f=classic&s=regular

**Comment by vadosnaprimer** [comment]
Not bad.

**Comment by nattthebear** [comment]
As proposed in this PR, it has to be a plain unicode character to be rendered in posts.  There's nowhere to put a font awesome.  There are other ways it could be implemented that would allow for that, but someone would have to do that first and it would be more complex and maybe not worth it.

**Comment by adelikat** [comment]
Note that this method will only apply to future posts created after this is deployed

**Comment by adelikat** [comment]
Thanks for the PR, but rather than merge I took the idea and did the actual icon in css instead of a baked in unicode character, and also changed it to a comment bubble as mentioned above

**Pull request closed without merging**
