### PR TITLE
Visited Links on Forum Threads and Last Posts

### LINKED ISSUE #510: Visited forum links stays blue instead of purple
Repro:
1. https://tasvideos.mistflux.net/Forum/Subforum/7
2. Click on a topic
3. Go back to previous page

The link should turn purple (visited) to help users maintain their progress of visiting various topics.

### PR DESCRIPTION
**Pull request by TiKevin83**
fixes #510 more precisely

I still disagree with the need to use a color other than purple, the purple visited style is pretty ubiquitous, willing to change it though if there's wider disagreement.

I updated the PR to only affect visited links on the forum thread links and last post links, it looks pretty useful to my eye.

### CODE REVIEW

**Comment by Masterjun3** [comment]
The problem with making post links colored is they don't get colored when you browse the forum by clicking on threads and advance pages to the latest post.
I dislike how this creates the illusion that purple = seen the post, and, blue = not seen the post, which isn't true in this design.

**Comment by vadosnaprimer** [comment]
Here's the current color difference (top not visited, bottom visited)

изображение

**Comment by Masterjun3** [comment]
> Is it about that while the thread you already visited becomes purple (edited) **even after** a new post has been made?

No.
It's about creating the illusion that purple means seen and blue means not seen. But this isn't true with this pull request.

**Comment by TiKevin83** [comment]
to be fair masterjun I'm not sure if that's a solvable problem, I think we'd be stuck between no visited link styling at all and the visited style not covering the "last post" unless you read it through that exact link.

**Comment by Masterjun3** [comment]
The visited link style works for threads, since you then know what thread you were in before.
But there is no need to make post links visisted. That's not how the site used to work, and it brings new issues.
A better way to separate new posts from old posts would be to use something similar to the "Posts since last visit" feature, not a browserside visited style.

**Comment by vadosnaprimer** [comment]
> The visited link style works for threads, since you then know what thread you were in before. But there is no need to make post links visisted. That's not how the site used to work, and it brings new issues. A better way to separate new posts from old posts would be to use something similar to the "Posts since last visit" feature, not a browserside visited style.

I agree with this.

**Comment by TiKevin83** [comment]
Updated PR to only affect threads and not last posts

**Pull request merged**
