### PR TITLE
Making only Experienced Forum Users be able to set signatures

### LINKED ISSUE #1517: Restrict signatures completely until an amount of posts.
Making it easier to go after bot accounts as there's some that commonly have their signatures display the spam material without ever posting.
Possibly only needs at least 4 (Newbie) posts...

### PR DESCRIPTION
**Pull request by GMPranav**
Resolves #1517

### CODE REVIEW

**Review by Masterjun3 — CHANGES_REQUESTED** [review]
Wasn't the point of our [Permission](https://github.com/TASVideos/tasvideos/blob/main/TASVideos.Data/Entity/PermissionTo.cs) system to add specific permissions instead of hardcoding roles?

**Comment by GMPranav** [comment]
I was only trying to implement @CasualPokePlayer's idea. I was not aware of that permission system and also find it hard to decipher it.

**Comment by adelikat** [comment]
@Masterjun3 is correct, we must add a new permission, and then check that permission when choosing to display things.

Checking roles means that a simple name change on a role can break functionality

**Comment by Masterjun3** [comment]
I know this is closed already, but I missed a very important part when writing my feedback:
This PR only changes the visibility of the according element in the HTML. A "malicious" user could just reinsert that specific part and be able to change their signature without problems.

In general our idea is to *never trust the user*, so permission things should **always** be done server-side.

**Comment by GMPranav** [comment]
Yeah, that was quite the dirty quickfix

**Comment by adelikat** [comment]
To be clear, having the code in the view is good, but it just needs the check server side on the POST call in addition

**Pull request closed without merging**
