### PR TITLE
Trim whitespace from block forum tags

### PR DESCRIPTION
**Pull request by nattthebear**
Sort of does what was asked for in #902

### CODE REVIEW

**Comment by nattthebear** [comment]
Could use some review here; not just for bugs, but decisions since there's no one right answer here.

**Comment by vadosnaprimer** [comment]
Can you post some pics please?

**Comment by Masterjun3** [comment]
I tried checking this out but for some reason it only works when clicking "Preview" and doesn't work in the actual post. Is that even possible or is my setup broken?

**Comment by adelikat** [comment]
I can confirm that there seems to be trimmed whitespace in the preview but not when you actually post

image

Actual post:
image

**Comment by nattthebear** [comment]
I see.  The problem seems to be that when creating a post, some part of the create process is mangling `\n` into `\r\n`, but no such braindead translation is happening in post preview.  Browsers universally never send `\r` as a part of any textarea content unless the user explicitly asks for it, so I think the best thing to do here is to fix the braindead mangling in post create.  Does anyone know what is doing this?

**Comment by adelikat** [comment]
All the logic is in Pages/Forums/Post/Create.cshtml.cs

**Comment by Masterjun3** [comment]
According to my browser log for the POST request, it does send \r\n.

image

**Comment by nattthebear** [comment]
Then why doesn't it do it on preview?  Guess I'm off to MDN to learn about some more random shit that IE4 did, so now everything does...

**Comment by nattthebear** [comment]
Ready for review again.  A textarea's `.value` always contains just `\n` and not `\r`.  The preview path takes the textarea's `.value` and manually assembles it as the sole body of a `POST`, so doesn't have a `\r`.  On the other hand, the post creation path uses 'multipart/form-data' which always represents newlines as `\r\n`.  One more reason to avoid that awful format, I suppose?

Anyway, for this ticket, I made post creation trim the `\r` since we won't ever need it, and made parsing resilient to the `\r` so we don't have to migrate existing posts.

Everything should be working now.

**Review by adelikat — APPROVED** [review]

**Pull request merged**
