### PR TITLE
fix mobile screen overflow of post creation button groups

### LINKED ISSUE #546: BBCode buttons clip through the sides when creating new posts or topics on mobile
Example page (view on mobile/small widths): https://demo.tasvideos.org/Forum/Posts/Create/22808

### PR DESCRIPTION
**Pull request by TiKevin83**
fix #546

### CODE REVIEW

**Comment by Masterjun3** [comment]
This change currently doesn't really look good:
image
Maybe make it stay at a size fitting for the text and put outlines around buttons.

**Review by Masterjun3 — CHANGES_REQUESTED** [review]
This change currently doesn't really look good:
image
Maybe make it stay at a size fitting for the text and put outlines around buttons.

**Comment by TiKevin83** [comment]
I've made it so the buttons no longer grow to fit the full width when wrapping and I've given them a border so they should be more easily distinguishable

**Comment by Masterjun3** [comment]
Nice, looks good. Any reason why the button groups aren't consistent? Some have the flex-wrap, others don't.

**Comment by TiKevin83** [comment]
Those groups shouldn't be affected by this problem except in unusably tiny screen widths so I think it's better to leave them

**Comment by Masterjun3** [comment]
Well, or if they have an increased font size, or if we decide to add more buttons. Can you explain why it's "better" to leave it?
Feels like a weird inconsistency.

**Comment by TiKevin83** [comment]
I could go either way on it but to me there's a design difference where some of these button groups are more like a button toolbar and the order and how close they are to each other doesn't matter, and the ones with fewer buttons are more tightly semantically connected and you wouldn't want a line to wrap with only one of them at a time

**Review by Masterjun3 — APPROVED** [review]

**Pull request merged**
