### PR TITLE
Add/Merge additional params on return urls

### PR DESCRIPTION
**Pull request by Masterjun3**
Resolves the bug where we would redirect to a page with two `?`, breaking the query.

To recreate the bug
- go to Submission Catalog
- click New next to Game to create a new game, enter some stuff, and Save
- you get redirected back, notice you're now on a url like `/Submissions/Catalog/7251?GameId=2356`
- click New next to Game Version to create a new version, enter some stuff, and Save
- you get redirected back again, notice you're now on a url like `/Submissions/Catalog/7251?GameId=2356?GameId=2356&GameVersionId=4820`

That's the bug, there are two `?` in that final link. Only the first `?` counts, so the query sets `GameId` to `2356?GameId=2356`.

~~After this PR the final link will look like `/Submissions/Catalog/7251?GameId=2356&GameId=2356&GameVersionId=4820`.
Notice how there are still two `GameId`s, but it works (and query string expliticly allow multiple settings of the same value).~~

After this PR the final link will look like `/Submissions/Catalog/7251?GameId=2356&GameVersionId=4820`.

### CODE REVIEW

**Comment by adelikat** [comment]
I like this approach, and the code looks good

**Comment by vadosnaprimer** [comment]
I'll test locally and call back.

**Comment by vadosnaprimer** [comment]
If I create game and version, they get properly selected. The baseline goal is created automatically, so I can just select it and save. But if I need to create a different goal and I hit Manage, game version gets unselected.

**Comment by Masterjun3** [comment]
Technically the Manage button is unrelated to this PR. But I found the reason this happens. It's because our javascript doesn't encode the return url properly. I can make a commit that fixes that as well.

**Comment by vadosnaprimer** [comment]
Thanks!

**Review by adelikat — APPROVED** [review]

**Pull request merged**
