### PR TITLE
Show total userfile count next to author

### LINKED ISSUE #895: Put user files amount and link in a user file page
Just as it used to be on old site. Example: https://tasvideos.org/UserFiles/ForUser/ThunderAxe31

Current:
image

Desired:
image

Note that you can see files amount and url from the [Profile page](https://tasvideos.org/Profile), but I'm too much noob to make the PR myself, sorry.
image

### PR DESCRIPTION
**Pull request by Masterjun3**
Resolves #895.

### CODE REVIEW

**Comment by Masterjun3** [comment]
Hold on!
This shows all userfiles, instead of just non-hidden ones like on the profile.

**Comment by Masterjun3** [comment]
It now counts only userfiles that aren't hidden. This requires calling Count() which is probably slower.

**Comment by adelikat** [comment]
It is calling Count() at the IQueryable level, which is fine, it will just figure out some sql that will include it in the query at a minor speed cost

**Review by adelikat — APPROVED** [review]

**Comment by Masterjun3** [comment]
These changes were made in pull request #898.

**Pull request closed without merging**
